apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-{{ .Values.shardId }}-data
  labels:
    app: sonarqube
    shard: {{ .Values.shardId | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.sonarSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-{{ .Values.shardId }}-pg-data
  labels:
    app: sonarqube
    shard: {{ .Values.shardId | quote }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.pgSize }}
