apiVersion: v1
kind: Service
metadata:
  name: sonar-{{ .Values.shardId }}
  labels:
    app: sonarqube
    shard: {{ .Values.shardId | quote }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: sonarqube
    shard: {{ .Values.shardId | quote }}
